export const exchangeFacadeABI = [
  { inputs: [], name: 'hyperliquidAddress', outputs: [{ name: '', type: 'address' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'getHyperliquidSpotBalance', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  { inputs: [], name: 'getExchangeAssetBalance', outputs: [{ name: '', type: 'uint256' }], stateMutability: 'view', type: 'function' },
  {
    inputs: [{ name: 'symbol', type: 'string' }],
    name: 'getHyperliquidPosition',
    outputs: [
      { name: 'size', type: 'uint256' },
      { name: 'collateral', type: 'uint256' },
      { name: 'entryPrice', type: 'uint256' },
      { name: 'isLong', type: 'bool' },
      { name: 'isActive', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [{ name: 'amount', type: 'uint256' }], name: 'depositToHyperliquid', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'amount', type: 'uint256' }], name: 'withdrawFromHyperliquid', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'amount', type: 'uint256' }], name: 'withdrawAssetFromHyperliquid', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'amount', type: 'uint256' }], name: 'addCollateralToHyperliquid', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'symbol', type: 'string' }, { name: 'size', type: 'uint256' }], name: 'openShort', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'symbol', type: 'string' }], name: 'closeShort', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'symbol', type: 'string' }, { name: 'closeSize', type: 'uint256' }], name: 'closeShort', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'usdcAmount', type: 'uint256' }], name: 'spotBuyOnHyperliquid', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'amount', type: 'uint256' }], name: 'spotSellOnHyperliquid', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'orderId', type: 'bytes32' }], name: 'cancelHyperliquidOrder', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { inputs: [{ name: 'adapter', type: 'address' }], name: 'setHyperliquid', outputs: [], stateMutability: 'nonpayable', type: 'function' },
] as const;
