// ABI for KashYieldETH contract (two-phase batch, ETH/wETH only)
export const kashYieldABI = [
  // Views
  { inputs: [], name: "getNAV", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getCurrentBatchCycle", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "cycleDurationSeconds", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "_seconds", type: "uint256" }], name: "setCycleDurationSeconds", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [
      { name: "user", type: "address" },
      { name: "batchCycle", type: "uint256" },
    ],
    name: "getPendingMintRequest",
    outputs: [
      {
        components: [
          { name: "user", type: "address" },
          { name: "amountIn", type: "uint256" },
          { name: "amountInUSD", type: "uint256" },
          { name: "batchCycle", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "user", type: "address" },
      { name: "batchCycle", type: "uint256" },
    ],
    name: "getPendingRedeemRequest",
    outputs: [
      {
        components: [
          { name: "user", type: "address" },
          { name: "kashAmount", type: "uint256" },
          { name: "batchCycle", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "batchCycle", type: "uint256" }],
    name: "getBatchInfo",
    outputs: [
      { name: "totalMintUSD", type: "uint256" },
      { name: "totalRedeemUSD", type: "uint256" },
      { name: "processed", type: "bool" },
      { name: "mintUsersCount", type: "uint256" },
      { name: "redeemUsersCount", type: "uint256" },
      { name: "totalRedeemKash", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ name: "batchCycle", type: "uint256" }, { name: "index", type: "uint256" }], name: "batchMintUsers", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }, { name: "index", type: "uint256" }], name: "batchRedeemUsers", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "batchPhase", outputs: [{ name: "", type: "uint8" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "batchProcessed", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "batchTotalMintBtc", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "batchTotalMintEth", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "batchMintBtcDeployedToAave", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "batchMintEthDeployedToAave", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "batchTotalRedeemKash", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "isProcessingWindow", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "isUserWindow", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "paused", outputs: [{ name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "feeBps", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "ownerUsdcReserve", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "ownerEthReserve", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "ownerWbtcReserve", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "protocolFeeEthReserve", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "protocolFeeWbtcReserve", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "coverUsdcShortfall", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "wethAddress", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "wbtcAddress", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "usdcAddress", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "currentNAV", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "kashTokenEth", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "kashTokenBtc", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getBtcPrice", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "aavePoolAddress", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "hyperliquidAddress", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "activePerpExchange", outputs: [{ name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "", type: "string" }], name: "perpExchanges", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getEthPrice", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getReservedEth", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getReservedBtc", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  // User + batch
  { inputs: [{ name: "amount", type: "uint256" }], name: "requestMint", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ name: "kashAmount", type: "uint256" }], name: "requestRedeem", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "cancelMintRequest", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "cancelRedeemRequest", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "performData", type: "bytes" }], name: "performUpkeep", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "processBatchPhase2ForCycle", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "markBatchOpsDone", outputs: [], stateMutability: "nonpayable", type: "function" },
  // Aave (ETH-only)
  { inputs: [{ name: "amount", type: "uint256" }], name: "depositToAave", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "withdrawFromAave", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "asset", type: "address" }, { name: "amount", type: "uint256" }], name: "borrowFromAave", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "asset", type: "address" }, { name: "amount", type: "uint256" }], name: "repayToAave", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "addCollateralToAave", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "spotDexAddress", outputs: [{ name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "swapForUsdc", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "usdcAmount", type: "uint256" }], name: "swapFromUsdc", outputs: [], stateMutability: "nonpayable", type: "function" },
  // Hyperliquid
  { inputs: [{ name: "_hyperliquidAddress", type: "address" }], name: "setHyperliquid", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "depositToHyperliquid", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "withdrawFromHyperliquid", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "addCollateralToHyperliquid", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "symbol", type: "string" }, { name: "size", type: "uint256" }], name: "openShort", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "symbol", type: "string" }], name: "closeShort", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "symbol", type: "string" }, { name: "closeSize", type: "uint256" }], name: "closeShort", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "usdcAmount", type: "uint256" }], name: "spotBuyOnHyperliquid", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "spotSellOnHyperliquid", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "withdrawBtcFromHyperliquid", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "withdrawEthFromHyperliquid", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "orderId", type: "bytes32" }], name: "cancelHyperliquidOrder", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "getHyperliquidSpotBalance", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  /** ETH or wBTC spot balance inside Hyperliquid (via IPerpExchange adapter account on the core mock). */
  { inputs: [], name: "getExchangeAssetBalance", outputs: [{ name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ name: "symbol", type: "string" }],
    name: "getHyperliquidPosition",
    outputs: [
      { name: "size", type: "uint256" },
      { name: "collateral", type: "uint256" },
      { name: "entryPrice", type: "uint256" },
      { name: "isLong", type: "bool" },
      { name: "isActive", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "getHyperliquidOpenOrderIds", outputs: [{ name: "", type: "bytes32[]" }], stateMutability: "view", type: "function" },
  // Admin
  { inputs: [{ name: "newNAV", type: "uint256" }, { name: "usdcBalance", type: "uint256" }, { name: "assetBalance", type: "uint256" }, { name: "perpPnL", type: "uint256" }], name: "updateNAV", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "newFee", type: "uint256" }], name: "setFeeBps", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_aavePool", type: "address" }], name: "setAavePool", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_weth", type: "address" }], name: "setWethAddress", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_usdc", type: "address" }], name: "setUsdcAddress", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_oracle", type: "address" }], name: "setEthOracle", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_botAddress", type: "address" }], name: "setBotAddress", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "_keeperRegistry", type: "address" }], name: "setKeeperRegistry", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "pause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "unpause", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }, { name: "amount", type: "uint256" }], name: "markMintBtcDeployed", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }, { name: "amount", type: "uint256" }], name: "markMintEthDeployed", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "ownerWithdrawEth", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "amount", type: "uint256" }], name: "ownerWithdrawWbtc", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "emergencyWithdrawMint", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ name: "batchCycle", type: "uint256" }], name: "emergencyWithdrawRedeem", outputs: [], stateMutability: "nonpayable", type: "function" },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amountIn", type: "uint256" },
      { indexed: false, name: "batchCycle", type: "uint256" },
    ],
    name: "MintRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "kashAmount", type: "uint256" },
      { indexed: false, name: "batchCycle", type: "uint256" },
    ],
    name: "RedeemRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "batchCycle", type: "uint256" },
      { indexed: false, name: "phase", type: "uint8" },
      { indexed: false, name: "indicativeNAV", type: "uint256" },
    ],
    name: "BatchPhaseUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "batchCycle", type: "uint256" },
      { indexed: false, name: "totalMintValueUSD", type: "uint256" },
      { indexed: false, name: "totalRedeemValueUSD", type: "uint256" },
      { indexed: false, name: "exactNAV", type: "uint256" },
    ],
    name: "BatchProcessed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "isMint", type: "bool" },
    ],
    name: "TokensClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "newNAV", type: "uint256" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
    name: "NAVUpdateExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "action", type: "uint8" },
      { indexed: true, name: "asset", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "ProtocolInteraction",
    type: "event",
  },
] as const;
