/**
 * Must match `contracts/libraries/ProtocolActionCodes.sol`.
 */
export const ProtocolAction = {
  CANCEL_MINT: 1,
  CANCEL_REDEEM: 2,
  NET_MINT: 3,
  NET_REDEEM: 4,
  REDEEM_TRANSFER_FAILED: 5,
  AAVE_DEPOSIT: 6,
  AAVE_WITHDRAW: 7,
  AAVE_BORROW: 8,
  AAVE_REPAY: 9,
  AAVE_ADD_COLLATERAL: 10,
  EXCHANGE_DEPOSIT: 11,
  EXCHANGE_WITHDRAW: 12,
  EXCHANGE_WITHDRAW_ASSET: 13,
  EXCHANGE_ADD_COLLATERAL: 14,
  EXCHANGE_OPEN_SHORT: 15,
  EXCHANGE_CLOSE_SHORT: 16,
  EXCHANGE_SPOT_BUY: 17,
  EXCHANGE_SPOT_SELL: 18,
  EXCHANGE_CANCEL_ORDER: 19,
  DEX_SWAP_FOR_USDC: 20,
  DEX_SWAP_FROM_USDC: 21,
  MINT_ETH_DEPLOYED: 22,
  MINT_BTC_DEPLOYED: 23,
  OWNER_WITHDRAW_ETH: 24,
  OWNER_WITHDRAW_WBTC: 25,
  RESCUE_ERC20: 26,
  OWNER_USDC_DEPOSIT: 27,
  OWNER_ETH_DEPOSIT: 28,
  OWNER_WBTC_DEPOSIT: 29,
  OWNER_USDC_COVER_SHORTFALL: 30,
} as const;

export type ProtocolActionCode = (typeof ProtocolAction)[keyof typeof ProtocolAction];

const NAMES: Record<number, string> = {
  1: 'CANCEL_MINT',
  2: 'CANCEL_REDEEM',
  3: 'NET_MINT',
  4: 'NET_REDEEM',
  5: 'REDEEM_TRANSFER_FAILED',
  6: 'AAVE_DEPOSIT',
  7: 'AAVE_WITHDRAW',
  8: 'AAVE_BORROW',
  9: 'AAVE_REPAY',
  10: 'AAVE_ADD_COLLATERAL',
  11: 'EXCHANGE_DEPOSIT',
  12: 'EXCHANGE_WITHDRAW',
  13: 'EXCHANGE_WITHDRAW_ASSET',
  14: 'EXCHANGE_ADD_COLLATERAL',
  15: 'EXCHANGE_OPEN_SHORT',
  16: 'EXCHANGE_CLOSE_SHORT',
  17: 'EXCHANGE_SPOT_BUY',
  18: 'EXCHANGE_SPOT_SELL',
  19: 'EXCHANGE_CANCEL_ORDER',
  20: 'DEX_SWAP_FOR_USDC',
  21: 'DEX_SWAP_FROM_USDC',
  22: 'MINT_ETH_DEPLOYED',
  23: 'MINT_BTC_DEPLOYED',
  24: 'OWNER_WITHDRAW_ETH',
  25: 'OWNER_WITHDRAW_WBTC',
  26: 'RESCUE_ERC20',
  27: 'OWNER_USDC_DEPOSIT',
  28: 'OWNER_ETH_DEPOSIT',
  29: 'OWNER_WBTC_DEPOSIT',
  30: 'OWNER_USDC_COVER_SHORTFALL',
};

export function protocolActionName(code: bigint | number): string {
  const n = typeof code === 'bigint' ? Number(code) : code;
  return NAMES[n] ?? `UNKNOWN(${n})`;
}
