export const kashYieldABI = [
  // Read functions
  {
    inputs: [],
    name: "currentNAV",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNAV",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isUserWindow",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isProcessingWindow",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeBps",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "user", type: "address" },
      { name: "batchCycle", type: "uint256" },
    ],
    name: "getPendingMintRequest",
    outputs: [
      {
        components: [
          { name: "user", type: "address" },
          { name: "amountIn", type: "uint256" },
          { name: "amountInUSD", type: "uint256" },
          { name: "batchCycle", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "user", type: "address" },
      { name: "batchCycle", type: "uint256" },
    ],
    name: "getPendingRedeemRequest",
    outputs: [
      {
        components: [
          { name: "user", type: "address" },
          { name: "kashAmount", type: "uint256" },
          { name: "batchCycle", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "batchCycle", type: "uint256" },
      { name: "index", type: "uint256" },
    ],
    name: "batchRedeemUsers",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "batchCycle", type: "uint256" }],
    name: "getBatchInfo",
    outputs: [
      { name: "totalMintUSD", type: "uint256" },
      { name: "totalRedeemUSD", type: "uint256" },
      { name: "processed", type: "bool" },
      { name: "mintUsersCount", type: "uint256" },
      { name: "redeemUsersCount", type: "uint256" },
      { name: "totalRedeemKash", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "batchCycle", type: "uint256" }],
    name: "batchPhase",
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getTotalDepositedBtc",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getTotalRedeemedBtc",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getTotalDepositedEth",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getTotalRedeemedEth",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentBatchCycle",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cycleDurationSeconds",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "_seconds", type: "uint256" }],
    name: "setCycleDurationSeconds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // Write functions
  {
    inputs: [
      { name: "amount", type: "uint256" },
    ],
    name: "requestMint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "kashAmount", type: "uint256" },
    ],
    name: "requestRedeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "batchCycle", type: "uint256" }],
    name: "cancelMintRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "batchCycle", type: "uint256" }],
    name: "cancelRedeemRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "batchCycle", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "proof", type: "bytes32[]" },
    ],
    name: "claimRedeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "batchCycle", type: "uint256" }, { name: "user", type: "address" }],
    name: "redeemClaimed",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "batchCycle", type: "uint256" }],
    name: "batchClaimInfo",
    outputs: [
      { name: "redeemMerkleRoot", type: "bytes32" },
      { name: "totalNetClaimable", type: "uint256" },
      { name: "claimDeadline", type: "uint256" },
      { name: "claimedAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amountIn", type: "uint256" },
      { indexed: false, name: "batchCycle", type: "uint256" },
    ],
    name: "MintRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "kashAmount", type: "uint256" },
      { indexed: false, name: "batchCycle", type: "uint256" },
    ],
    name: "RedeemRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "batchCycle", type: "uint256" },
      { indexed: false, name: "totalMintValueUSD", type: "uint256" },
      { indexed: false, name: "totalRedeemValueUSD", type: "uint256" },
      { indexed: false, name: "exactNAV", type: "uint256" },
    ],
    name: "BatchProcessed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "token", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "isMint", type: "bool" },
    ],
    name: "TokensClaimed",
    type: "event",
  },
] as const;
